### ISSUE TITLE
Error in `ohsome2label image` command with Sentinel image from SentineHub

### ISSUE THREAD

**Issue by LorenzoStucchi** [GIScience/ohsome2label#10]
During the execution of the comand `ohsome2label --config config\config.yaml image` with the following file `config.ymal`:

```yml
project:
  name: TestSentinel
  workspace: ./Sentinel_result
  project_time: 2020-05-18
  task: segmentation

osm:
  api: ohsome
  url: https://api.ohsome.org/v1/elements/geometry
  bboxes: [8.625,49.3711,8.7334,49.4397]
  tags:
    - {'label': 'urban', 'key': 'landuse', 'value': 'residential'}
    - {'label': 'urban', 'key': 'landuse', 'value': 'garages'}
    - {'label': 'industry', 'key': 'landuse', 'value': 'railway'}
    - {'label': 'industry', 'key': 'landuse', 'value': 'industrial'}

  timestamp: 2019-10-20
  types: polygon

image:
  img_api: sentinel
  img_url: https://services.sentinel-hub.com/ogc/wms/{token}?showLogo=false&service=WMS&request=GetMap&layers=ALL-BAND&styles=&format=image%2Ftiff&transparent=1&version=1.1.1&maxcc=20&time=2015-01-01%2F2020-01-01&priority=mostRecent&height=256&width=256&srs=EPSG%3A3857&bbox={bbox}
  api_token : 'TOKEN'
  zoom: 14
```

It provided the error below. I never use the operator <<, so I'm not confident in fixing it. From the guide seems that `n = 1 << int(tile.z)` could fix it, but this will produce other errors.

```
  File "c:\users\stucchi\documents\github\ohsome2label\ohsome2label\tile.py", line 148, in top_left
    n = 1 << tile.z
TypeError: unsupported operand type(s) for <<: 'int' and 'str'
```

I used python 3.6.8 and shapely 1.7.1, the suggested version of shapely (1.6.4) is not working and provides multiple errors. The 1.7.1 works in the command `vector` and `label`.
